server:
  port: 8084

spring:
  application:
    name: notification-service

aws:
  region: eu-central-1
  sqs:
    queue-url: disabled   # activado no profile docker

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
